2022-02-08 16:44:01,943 INFO    MainThread:404406 [wandb_setup.py:_flush():71] setting env: {}
2022-02-08 16:44:01,943 INFO    MainThread:404406 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-08 16:44:01,943 INFO    MainThread:404406 [wandb_init.py:_log_setup():371] Logging user logs to /home/stephen/Documents/3DDet/tools/wandb/run-20220208_164401-18hp61ov/logs/debug.log
2022-02-08 16:44:01,943 INFO    MainThread:404406 [wandb_init.py:_log_setup():372] Logging internal logs to /home/stephen/Documents/3DDet/tools/wandb/run-20220208_164401-18hp61ov/logs/debug-internal.log
2022-02-08 16:44:01,943 INFO    MainThread:404406 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f5ff61c0160>
2022-02-08 16:44:01,943 INFO    MainThread:404406 [wandb_init.py:init():404] calling init triggers
2022-02-08 16:44:01,943 INFO    MainThread:404406 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-02-08 16:44:01,943 INFO    MainThread:404406 [wandb_init.py:init():460] starting backend
2022-02-08 16:44:01,943 INFO    MainThread:404406 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-08 16:44:01,945 INFO    MainThread:404406 [backend.py:ensure_launched():216] starting backend process...
2022-02-08 16:44:01,954 INFO    MainThread:404406 [backend.py:ensure_launched():221] started backend process with pid: 413775
2022-02-08 16:44:01,955 INFO    MainThread:404406 [wandb_init.py:init():469] backend started and connected
2022-02-08 16:44:01,966 INFO    MainThread:404406 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-02-08 16:44:01,966 INFO    MainThread:404406 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-08 16:44:01,966 INFO    MainThread:404406 [wandb_init.py:init():533] updated telemetry
2022-02-08 16:44:01,989 INFO    MainThread:404406 [wandb_init.py:init():563] communicating current version
2022-02-08 16:44:02,644 INFO    MainThread:404406 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-08 16:44:02,646 INFO    MainThread:404406 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-08 16:44:02,862 INFO    MainThread:404406 [wandb_init.py:init():606] starting run threads in backend
2022-02-08 16:44:05,076 INFO    MainThread:404406 [wandb_run.py:_console_start():1810] atexit reg
2022-02-08 16:44:05,077 INFO    MainThread:404406 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-02-08 16:44:05,077 INFO    MainThread:404406 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-02-08 16:44:05,078 INFO    MainThread:404406 [wandb_run.py:_redirect():1745] Redirects installed.
2022-02-08 16:44:05,078 INFO    MainThread:404406 [wandb_init.py:init():633] run started, returning control to user process
2022-02-08 16:44:05,078 INFO    MainThread:404406 [wandb_run.py:_config_callback():956] config_cb None None {}
2022-02-08 16:44:05,078 INFO    MainThread:404406 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-08 16:44:05,079 INFO    MainThread:404406 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 16:44:07,769 INFO    MainThread:404406 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-08 16:44:07,773 INFO    MainThread:404406 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-08 16:44:07,773 INFO    MainThread:404406 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 16:44:14,628 INFO    MainThread:404406 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-08 16:44:15,018 INFO    MainThread:404406 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-08 16:44:15,019 INFO    MainThread:404406 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 16:45:10,904 INFO    MainThread:404406 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-08 16:45:10,925 INFO    MainThread:404406 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-08 16:45:10,925 INFO    MainThread:404406 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 16:45:17,199 INFO    MainThread:404406 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-08 16:45:17,201 INFO    MainThread:404406 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-08 16:45:17,201 INFO    MainThread:404406 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 16:45:17,607 INFO    MainThread:404406 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-08 16:45:17,636 INFO    MainThread:404406 [wandb_setup.py:_flush():71] setting env: {}
2022-02-08 16:45:17,636 INFO    MainThread:404406 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-08 16:45:17,636 INFO    MainThread:404406 [wandb_init.py:_log_setup():371] Logging user logs to /home/stephen/Documents/3DDet/tools/wandb/run-20220208_164517-3cyd5r94/logs/debug.log
2022-02-08 16:45:17,636 INFO    MainThread:404406 [wandb_init.py:_log_setup():372] Logging internal logs to /home/stephen/Documents/3DDet/tools/wandb/run-20220208_164517-3cyd5r94/logs/debug-internal.log
2022-02-08 16:45:17,636 INFO    MainThread:404406 [wandb_init.py:init():404] calling init triggers
2022-02-08 16:45:17,636 INFO    MainThread:404406 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-02-08 16:45:17,637 INFO    MainThread:404406 [wandb_init.py:init():424] re-initializing run, found existing run on stack: 18hp61ov
2022-02-08 16:45:17,638 INFO    MainThread:404406 [wandb_run.py:finish():1457] finishing run nelsonsw5/3DDet_Viz/18hp61ov
2022-02-08 16:45:17,638 INFO    MainThread:404406 [jupyter.py:save_history():429] not saving jupyter history
2022-02-08 16:45:17,639 INFO    MainThread:404406 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 16:45:17,639 INFO    MainThread:404406 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-02-08 16:45:17,639 INFO    MainThread:404406 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-02-08 16:45:17,640 INFO    MainThread:404406 [wandb_run.py:_restore():1752] restore
2022-02-08 16:45:18,162 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 1074
}

2022-02-08 16:45:18,305 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 1074
}

2022-02-08 16:45:18,514 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 1074
}

2022-02-08 16:45:18,905 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 11641
}

2022-02-08 16:45:19,009 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 11641
}

2022-02-08 16:45:19,113 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 11641
}

2022-02-08 16:45:19,215 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1436
  total_bytes: 11641
}

2022-02-08 16:45:19,317 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1436
  total_bytes: 11641
}

2022-02-08 16:45:19,420 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1436
  total_bytes: 11641
}

2022-02-08 16:45:19,522 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1436
  total_bytes: 11641
}

2022-02-08 16:45:19,624 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11641
  total_bytes: 11641
}

2022-02-08 16:45:19,728 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11641
  total_bytes: 11641
}

2022-02-08 16:45:19,830 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11641
  total_bytes: 11641
}

2022-02-08 16:45:19,932 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11641
  total_bytes: 11641
}

2022-02-08 16:45:20,241 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11641
  total_bytes: 11641
}

2022-02-08 16:45:20,672 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11641
  total_bytes: 11641
}
local_info {
}

2022-02-08 16:45:21,805 INFO    MainThread:404406 [wandb_run.py:_append_files():2180] logging synced files
