2022-02-08 21:43:39,745 INFO    MainThread:423389 [wandb_setup.py:_flush():71] setting env: {}
2022-02-08 21:43:39,745 INFO    MainThread:423389 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-08 21:43:39,745 INFO    MainThread:423389 [wandb_init.py:_log_setup():371] Logging user logs to /home/stephen/Documents/3DDet/tools/wandb/run-20220208_214339-iqulc3sm/logs/debug.log
2022-02-08 21:43:39,745 INFO    MainThread:423389 [wandb_init.py:_log_setup():372] Logging internal logs to /home/stephen/Documents/3DDet/tools/wandb/run-20220208_214339-iqulc3sm/logs/debug-internal.log
2022-02-08 21:43:39,745 INFO    MainThread:423389 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f42cc615d90>
2022-02-08 21:43:39,746 INFO    MainThread:423389 [wandb_init.py:init():404] calling init triggers
2022-02-08 21:43:39,746 INFO    MainThread:423389 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-02-08 21:43:39,746 INFO    MainThread:423389 [wandb_init.py:init():460] starting backend
2022-02-08 21:43:39,746 INFO    MainThread:423389 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-08 21:43:39,748 INFO    MainThread:423389 [backend.py:ensure_launched():216] starting backend process...
2022-02-08 21:43:39,760 INFO    MainThread:423389 [backend.py:ensure_launched():221] started backend process with pid: 424127
2022-02-08 21:43:39,761 INFO    MainThread:423389 [wandb_init.py:init():469] backend started and connected
2022-02-08 21:43:39,773 INFO    MainThread:423389 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-02-08 21:43:39,773 INFO    MainThread:423389 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-08 21:43:39,773 INFO    MainThread:423389 [wandb_init.py:init():533] updated telemetry
2022-02-08 21:43:39,805 INFO    MainThread:423389 [wandb_init.py:init():563] communicating current version
2022-02-08 21:43:40,465 INFO    MainThread:423389 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-08 21:43:40,467 INFO    MainThread:423389 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-08 21:43:40,927 INFO    MainThread:423389 [wandb_init.py:init():606] starting run threads in backend
2022-02-08 21:43:42,998 INFO    MainThread:423389 [wandb_run.py:_console_start():1810] atexit reg
2022-02-08 21:43:42,999 INFO    MainThread:423389 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-02-08 21:43:42,999 INFO    MainThread:423389 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-02-08 21:43:43,001 INFO    MainThread:423389 [wandb_run.py:_redirect():1745] Redirects installed.
2022-02-08 21:43:43,001 INFO    MainThread:423389 [wandb_init.py:init():633] run started, returning control to user process
2022-02-08 21:43:43,001 INFO    MainThread:423389 [wandb_run.py:_config_callback():956] config_cb None None {}
2022-02-08 21:43:43,034 INFO    MainThread:423389 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-08 21:43:43,034 INFO    MainThread:423389 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 21:45:52,579 INFO    MainThread:423389 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-08 21:45:52,592 INFO    MainThread:423389 [wandb_setup.py:_flush():71] setting env: {}
2022-02-08 21:45:52,592 INFO    MainThread:423389 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-08 21:45:52,592 INFO    MainThread:423389 [wandb_init.py:_log_setup():371] Logging user logs to /home/stephen/Documents/3DDet/tools/wandb/run-20220208_214552-3f3dasn8/logs/debug.log
2022-02-08 21:45:52,592 INFO    MainThread:423389 [wandb_init.py:_log_setup():372] Logging internal logs to /home/stephen/Documents/3DDet/tools/wandb/run-20220208_214552-3f3dasn8/logs/debug-internal.log
2022-02-08 21:45:52,593 INFO    MainThread:423389 [wandb_init.py:init():404] calling init triggers
2022-02-08 21:45:52,593 INFO    MainThread:423389 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-02-08 21:45:52,593 INFO    MainThread:423389 [wandb_init.py:init():424] re-initializing run, found existing run on stack: iqulc3sm
2022-02-08 21:45:52,594 INFO    MainThread:423389 [wandb_run.py:finish():1457] finishing run nelsonsw5/3DDet_Viz/iqulc3sm
2022-02-08 21:45:52,594 INFO    MainThread:423389 [jupyter.py:save_history():429] not saving jupyter history
2022-02-08 21:45:52,595 INFO    MainThread:423389 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 21:45:52,595 INFO    MainThread:423389 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-02-08 21:45:52,595 INFO    MainThread:423389 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-02-08 21:45:52,596 INFO    MainThread:423389 [wandb_run.py:_restore():1752] restore
2022-02-08 21:45:53,156 INFO    MainThread:423389 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 1074
}

2022-02-08 21:45:53,320 INFO    MainThread:423389 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 1074
}

2022-02-08 21:45:53,596 INFO    MainThread:423389 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 1074
}

2022-02-08 21:45:53,980 INFO    MainThread:423389 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 11641
}

2022-02-08 21:45:54,085 INFO    MainThread:423389 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 11641
}

2022-02-08 21:45:54,187 INFO    MainThread:423389 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 11641
}

2022-02-08 21:45:54,301 INFO    MainThread:423389 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 11641
}

2022-02-08 21:45:54,403 INFO    MainThread:423389 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 11641
}

2022-02-08 21:45:54,505 INFO    MainThread:423389 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11641
  total_bytes: 11641
}

2022-02-08 21:45:54,609 INFO    MainThread:423389 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11641
  total_bytes: 11641
}

2022-02-08 21:45:54,712 INFO    MainThread:423389 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11641
  total_bytes: 11641
}

2022-02-08 21:45:54,814 INFO    MainThread:423389 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11641
  total_bytes: 11641
}

2022-02-08 21:45:55,233 INFO    MainThread:423389 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11641
  total_bytes: 11641
}

2022-02-08 21:45:55,863 INFO    MainThread:423389 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11641
  total_bytes: 11641
}
local_info {
}

2022-02-08 21:45:56,973 INFO    MainThread:423389 [wandb_run.py:_append_files():2180] logging synced files
