2022-02-10 14:41:10,969 INFO    MainThread:589141 [wandb_setup.py:_flush():71] setting env: {}
2022-02-10 14:41:10,969 INFO    MainThread:589141 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-10 14:41:10,969 INFO    MainThread:589141 [wandb_init.py:_log_setup():371] Logging user logs to /home/stephen/Documents/3DDet/tools/wandb/run-20220210_144110-1huon7rz/logs/debug.log
2022-02-10 14:41:10,969 INFO    MainThread:589141 [wandb_init.py:_log_setup():372] Logging internal logs to /home/stephen/Documents/3DDet/tools/wandb/run-20220210_144110-1huon7rz/logs/debug-internal.log
2022-02-10 14:41:10,970 INFO    MainThread:589141 [wandb_init.py:init():404] calling init triggers
2022-02-10 14:41:10,970 INFO    MainThread:589141 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-02-10 14:41:10,970 INFO    MainThread:589141 [wandb_init.py:init():424] re-initializing run, found existing run on stack: 3ncmbtl7
2022-02-10 14:41:10,970 INFO    MainThread:589141 [wandb_run.py:finish():1457] finishing run nelsonsw5/3DDet_Viz/3ncmbtl7
2022-02-10 14:41:10,971 INFO    MainThread:589141 [jupyter.py:save_history():429] not saving jupyter history
2022-02-10 14:41:10,971 INFO    MainThread:589141 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-10 14:41:10,971 INFO    MainThread:589141 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-02-10 14:41:10,971 INFO    MainThread:589141 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-02-10 14:41:10,972 INFO    MainThread:589141 [wandb_run.py:_restore():1752] restore
2022-02-10 14:41:11,866 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 1074
}

2022-02-10 14:41:12,071 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 1074
}

2022-02-10 14:41:12,786 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 11653
}

2022-02-10 14:41:12,890 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 11653
}

2022-02-10 14:41:12,992 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7917
  total_bytes: 11653
}

2022-02-10 14:41:13,095 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11653
  total_bytes: 11653
}

2022-02-10 14:41:13,198 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11653
  total_bytes: 11653
}

2022-02-10 14:41:13,299 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11653
  total_bytes: 11653
}

2022-02-10 14:41:13,401 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11653
  total_bytes: 11653
}

2022-02-10 14:41:13,503 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11653
  total_bytes: 11653
}

2022-02-10 14:41:13,754 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11653
  total_bytes: 11653
}

2022-02-10 14:41:14,016 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11653
  total_bytes: 11653
}
local_info {
}

2022-02-10 14:41:15,127 INFO    MainThread:589141 [wandb_run.py:_append_files():2180] logging synced files
2022-02-10 14:41:15,133 INFO    MainThread:589141 [wandb_init.py:init():460] starting backend
2022-02-10 14:41:15,133 INFO    MainThread:589141 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-10 14:41:15,138 INFO    MainThread:589141 [backend.py:ensure_launched():216] starting backend process...
2022-02-10 14:41:15,151 INFO    MainThread:589141 [backend.py:ensure_launched():221] started backend process with pid: 591301
2022-02-10 14:41:15,152 INFO    MainThread:589141 [wandb_init.py:init():469] backend started and connected
2022-02-10 14:41:15,167 INFO    MainThread:589141 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-02-10 14:41:15,167 INFO    MainThread:589141 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-10 14:41:15,167 INFO    MainThread:589141 [wandb_init.py:init():533] updated telemetry
2022-02-10 14:41:15,196 INFO    MainThread:589141 [wandb_init.py:init():563] communicating current version
2022-02-10 14:41:15,806 INFO    MainThread:589141 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-10 14:41:15,808 INFO    MainThread:589141 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-10 14:41:15,955 INFO    MainThread:589141 [wandb_init.py:init():606] starting run threads in backend
2022-02-10 14:41:18,021 INFO    MainThread:589141 [wandb_run.py:_console_start():1810] atexit reg
2022-02-10 14:41:18,022 INFO    MainThread:589141 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-02-10 14:41:18,022 INFO    MainThread:589141 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-02-10 14:41:18,023 INFO    MainThread:589141 [wandb_run.py:_redirect():1745] Redirects installed.
2022-02-10 14:41:18,023 INFO    MainThread:589141 [wandb_init.py:init():633] run started, returning control to user process
2022-02-10 14:41:18,023 INFO    MainThread:589141 [wandb_run.py:_config_callback():956] config_cb None None {}
2022-02-10 14:42:33,426 INFO    MainThread:589141 [wandb_setup.py:_flush():71] setting env: {}
2022-02-10 14:42:33,427 INFO    MainThread:589141 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-10 14:42:33,427 INFO    MainThread:589141 [wandb_init.py:_log_setup():371] Logging user logs to /home/stephen/Documents/3DDet/tools/wandb/run-20220210_144233-2clnnz59/logs/debug.log
2022-02-10 14:42:33,427 INFO    MainThread:589141 [wandb_init.py:_log_setup():372] Logging internal logs to /home/stephen/Documents/3DDet/tools/wandb/run-20220210_144233-2clnnz59/logs/debug-internal.log
2022-02-10 14:42:33,427 INFO    MainThread:589141 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fc4120e4340>
2022-02-10 14:42:33,427 INFO    MainThread:589141 [wandb_init.py:init():404] calling init triggers
2022-02-10 14:42:33,427 INFO    MainThread:589141 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-02-10 14:42:33,427 INFO    MainThread:589141 [wandb_init.py:init():424] re-initializing run, found existing run on stack: 1huon7rz
2022-02-10 14:42:33,428 INFO    MainThread:589141 [wandb_run.py:finish():1457] finishing run nelsonsw5/3DDet_Viz/1huon7rz
2022-02-10 14:42:33,429 INFO    MainThread:589141 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-02-10 14:42:33,430 INFO    MainThread:589141 [wandb_run.py:_restore():1752] restore
2022-02-10 14:42:34,108 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 1074
}

2022-02-10 14:42:34,234 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 1074
}

2022-02-10 14:42:34,350 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 1074
}

2022-02-10 14:42:35,003 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 12577
}

2022-02-10 14:42:35,110 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 12577
}

2022-02-10 14:42:35,212 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 2009
  total_bytes: 12577
}

2022-02-10 14:42:35,314 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 8852
  total_bytes: 12577
}

2022-02-10 14:42:35,417 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12214
  total_bytes: 12577
}

2022-02-10 14:42:35,519 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12577
  total_bytes: 12577
}

2022-02-10 14:42:35,621 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12577
  total_bytes: 12577
}

2022-02-10 14:42:35,722 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12577
  total_bytes: 12577
}

2022-02-10 14:42:35,824 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12577
  total_bytes: 12577
}

2022-02-10 14:42:35,977 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12577
  total_bytes: 12577
}

2022-02-10 14:42:36,256 INFO    MainThread:589141 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12577
  total_bytes: 12577
}
local_info {
}

2022-02-10 14:42:37,380 INFO    MainThread:589141 [wandb_run.py:_append_files():2180] logging synced files
