2022-02-08 16:29:34,928 INFO    MainThread:404406 [wandb_setup.py:_flush():71] setting env: {}
2022-02-08 16:29:34,928 INFO    MainThread:404406 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-08 16:29:34,928 INFO    MainThread:404406 [wandb_init.py:_log_setup():371] Logging user logs to /home/stephen/Documents/3DDet/tools/wandb/run-20220208_162934-oyexqza1/logs/debug.log
2022-02-08 16:29:34,928 INFO    MainThread:404406 [wandb_init.py:_log_setup():372] Logging internal logs to /home/stephen/Documents/3DDet/tools/wandb/run-20220208_162934-oyexqza1/logs/debug-internal.log
2022-02-08 16:29:34,929 INFO    MainThread:404406 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f616c73c460>
2022-02-08 16:29:34,929 INFO    MainThread:404406 [wandb_init.py:init():404] calling init triggers
2022-02-08 16:29:34,929 INFO    MainThread:404406 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-02-08 16:29:34,929 INFO    MainThread:404406 [wandb_init.py:init():460] starting backend
2022-02-08 16:29:34,929 INFO    MainThread:404406 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-08 16:29:34,942 INFO    MainThread:404406 [backend.py:ensure_launched():216] starting backend process...
2022-02-08 16:29:34,952 INFO    MainThread:404406 [backend.py:ensure_launched():221] started backend process with pid: 404539
2022-02-08 16:29:34,953 INFO    MainThread:404406 [wandb_init.py:init():469] backend started and connected
2022-02-08 16:29:34,965 INFO    MainThread:404406 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-02-08 16:29:34,965 INFO    MainThread:404406 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-08 16:29:34,965 INFO    MainThread:404406 [wandb_init.py:init():533] updated telemetry
2022-02-08 16:29:34,999 INFO    MainThread:404406 [wandb_init.py:init():563] communicating current version
2022-02-08 16:29:35,632 INFO    MainThread:404406 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-08 16:29:35,632 INFO    MainThread:404406 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-08 16:29:35,820 INFO    MainThread:404406 [wandb_init.py:init():606] starting run threads in backend
2022-02-08 16:29:38,096 INFO    MainThread:404406 [wandb_run.py:_console_start():1810] atexit reg
2022-02-08 16:29:38,096 INFO    MainThread:404406 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-02-08 16:29:38,097 INFO    MainThread:404406 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-02-08 16:29:38,097 INFO    MainThread:404406 [wandb_run.py:_redirect():1745] Redirects installed.
2022-02-08 16:29:38,097 INFO    MainThread:404406 [wandb_init.py:init():633] run started, returning control to user process
2022-02-08 16:29:38,098 INFO    MainThread:404406 [wandb_run.py:_config_callback():956] config_cb None None {}
2022-02-08 16:29:38,098 INFO    MainThread:404406 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-08 16:29:38,098 INFO    MainThread:404406 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 16:29:43,426 INFO    MainThread:404406 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-08 16:29:43,455 INFO    MainThread:404406 [wandb_run.py:finish():1457] finishing run nelsonsw5/3DDet_Viz/oyexqza1
2022-02-08 16:29:43,496 INFO    MainThread:404406 [jupyter.py:save_history():429] not saving jupyter history
2022-02-08 16:29:43,497 INFO    MainThread:404406 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 16:29:43,497 INFO    MainThread:404406 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-02-08 16:29:43,497 INFO    MainThread:404406 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-02-08 16:29:43,498 INFO    MainThread:404406 [wandb_run.py:_restore():1752] restore
2022-02-08 16:29:44,111 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 1074
}

2022-02-08 16:29:44,236 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 1074
}

2022-02-08 16:29:44,432 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 1074
}

2022-02-08 16:29:44,850 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 11641
}

2022-02-08 16:29:44,953 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 11641
}

2022-02-08 16:29:45,056 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 11641
}

2022-02-08 16:29:45,158 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11641
  total_bytes: 11641
}

2022-02-08 16:29:45,261 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11641
  total_bytes: 11641
}

2022-02-08 16:29:45,363 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11641
  total_bytes: 11641
}

2022-02-08 16:29:45,465 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11641
  total_bytes: 11641
}

2022-02-08 16:29:45,797 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11641
  total_bytes: 11641
}

2022-02-08 16:29:46,240 INFO    MainThread:404406 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11641
  total_bytes: 11641
}
local_info {
}

2022-02-08 16:29:47,372 INFO    MainThread:404406 [wandb_run.py:_append_files():2180] logging synced files
